language: node_js
os: linux
dist: bionic
node_js:
  - lts/*
install:
  - yarn global add lerna
  - yarn run lerna:bootstrap
  - yarn run tsc
jobs:
  include:
    # 测试并部署 DEMO
    - stage: demo-deploy
      name: "Test and Deploy Theme Demo Test"
      script:
        - yarn run theme-test:build
      deploy:
        provider: pages
        local_dir: tests/dist
        token: $Github_Token
        repo: Mister-Hope/theme-demo
        fqdn: vuepress-theme-demo.mrhope.site
        edge: true
        strategy: git
        on:
          all_branches: true

    # 部署文档
    - stage: deploy-docs
      # 部署评论文档
      name: "Build and Deploy Comment Docs"
      script:
        - yarn run comment-docs:build
      deploy:
        provider: pages
        local_dir: docs/comment/dist
        token: $Github_Token
        repo: Mister-Hope/vuepress-plugin-comment-docs
        fqdn: vuepress-comment.mrhope.site
        edge: true
        strategy: git

    # 部署 Markdown 增强文档
    - name: "Build and Deploy Markdown Enhance Docs"
      script:
        - yarn run md-enhance-docs:build
      deploy:
        provider: pages
        local_dir: docs/md-enhance/dist
        token: $Github_Token
        repo: Mister-Hope/vuepress-plugin-md-enhance-docs
        fqdn: vuepress-md-enhance.mrhope.site
        edge: true
        strategy: git

    # 部署文档
    - name: "Build and Deploy Offical Docs"
      script:
        - yarn run theme:build
      deploy:
        provider: pages
        local_dir: docs/theme/dist
        token: $Github_Token
        fqdn: vuepress-theme.mrhope.site
        edge: true
        strategy: git

    # 测试 主题
    - stage: theme-test
      name: "Test Theme"
      script:
        - yarn run md-enhance:test
        - yarn run theme:test

stages:
  - name: demo-deploy
  - name: theme-test
  - name: deploy-docs
    if: branch = master
