language: node_js
node_js:
  - lts/*
install:
  - yarn install
  - npm run lerna:bootstrap
jobs:
  include:
    # 测试 shared-utils
    - stage: test-shared-utils
      name: "Test shared utils"
      script:
        - npm run share-utils:test

    # 测试并部署 DEMO
    - stage: demo
      name: "Test and Deploy Demo"
      script:
        - npm run test:copy
        - npm run test:build
      before_deploy: echo theme-demo.mrhope.site >> packages/theme/tests/demo-dist/CNAME
      deploy:
        provider: pages
        skip-cleanup: true
        local_dir: packages/theme/tests/demo-dist
        github-token: $Github_Token
        repo: Mister-Hope/theme-demo
        on:
          all_branches: true

    # 部署评论文档
    - stage: comment-doc
      name: "Deploy Comment Docs"
      script:
        - npm run comment:build
      before_deploy: echo comment.mrhope.site >> docs/dist/comment/CNAME
      deploy:
        provider: pages
        skip-cleanup: true
        local_dir: docs/dist/comment
        github-token: $Github_Token
        repo: Mister-Hope/vuepress-plugin-comment-docs

    # 部署文档
    - stage: deploy-docs
      name: "Deploy Offical Docs"
      script:
        - npm run theme:build
      before_deploy: echo vuepress-theme.mrhope.site >> docs/dist/theme/CNAME
      deploy:
        provider: pages
        skip-cleanup: true
        local_dir: docs/dist/theme
        github-token: $Github_Token

stages:
  - name: test-shared-utils
  - name: demo
  - name: comment-doc
    if: branch = master
  - name: deploy-docs
    if: branch = master
