name: Deploy Production Docs and Demos

on:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  deploy-netlify-docs:
    name: Deploy V2 docs to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore Build Result
        uses: actions/download-artifact@v4
        with:
          name: build-result

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Docs build
        env:
          NETLIFY: true
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run docs:vite-build

      - name: Deploy components docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/components-docs
          branch: netlify
          folder: docs/components/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

      - name: Deploy lightgallery docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/lightgallery-docs
          branch: netlify
          folder: docs/lightgallery/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

      - name: Deploy md-enhance docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/md-enhance-docs
          branch: netlify
          folder: docs/md-enhance/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

      - name: Deploy sass-palette docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/sass-palette-docs
          branch: netlify
          folder: docs/sass-palette/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

      - name: Deploy search-pro docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/search-pro-docs
          branch: netlify
          folder: docs/search-pro/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

      - name: Deploy shared docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/shared-docs
          branch: netlify
          folder: docs/shared/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

      - name: Deploy theme docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v2-theme-docs
          branch: netlify
          folder: docs/theme/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

  deploy-gitee-docs:
    name: Deploy V2 docs to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore Build Result
        uses: actions/download-artifact@v4
        with:
          name: build-result

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Docs build
        env:
          GITEE: true
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run docs:vite-build

      - name: Combine output
        run: |
          pnpm cpx "docs/components/dist/**" dist/components
          pnpm cpx "docs/lightgallery/dist/**" dist/lightgallery
          pnpm cpx "docs/md-enhance/dist/**" dist/md-enhance
          pnpm cpx "docs/sass-palette/dist/**" dist/sass-palette
          pnpm cpx "docs/search-pro/dist/**" dist/search-pro
          pnpm cpx "docs/shared/dist/**" dist/shared
          pnpm cpx "docs/theme/dist/**" dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v2
          branch: gitee
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

  deploy-theme-demo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
          - blog
          - docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore Build Result
        uses: actions/download-artifact@v4
        with:
          name: build-result

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build Netlify Demo
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm --filter theme-${{ matrix.name }}-demo demo:vite-build
          > demo/theme-${{ matrix.name }}/dist/.nojekyll

      - name: Deploy to netlify
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/${{ matrix.name }}-demo
          branch: netlify
          folder: demo/theme-${{ matrix.name }}/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

      - name: Build Gitee Demo
        env:
          BASE: /${{ matrix.name }}-demo/
          HOSTNAME: https://vuepress-theme-hope.gitee.io/
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm --filter theme-${{ matrix.name }}-demo demo:vite-build
          > demo/theme-${{ matrix.name }}/dist/.nojekyll

      - name: Deploy to gitee
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/${{ matrix.name }}-demo
          branch: gitee
          folder: demo/theme-${{ matrix.name }}/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

  deploy-plugin-demo:
    name: Deploy ${{ matrix.plugin-name }} demo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plugin-name:
          - components
          - lightgallery
          - md-enhance
          - sass-palette
          - search-pro

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore Build Result
        uses: actions/download-artifact@v4
        with:
          name: build-result

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build ${{ matrix.plugin-name }} demo
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm --filter ${{ matrix.plugin-name }}-demo demo:vite-build

      - name: Deploy ${{ matrix.plugin-name }} demo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/${{ matrix.plugin-name }}-demo
          branch: netlify
          folder: demo/${{ matrix.plugin-name }}/src/.vuepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true
