name: Publish packages and deploy Docs and Demos

on:
  push:
    tags:
      - v2.**

jobs:
  publish:
    name: Publish packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run build

      - name: Set Token
        run: |-
          echo "registry=https://registry.npmjs.org/
          //registry.npmjs.org/:always-auth=true
          //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: Publish packages
        run: pnpm publish -r --tag next --no-git-checks

      - name: Sync npmmirror
        run: pnpm release:sync

  deploy-netlify-docs:
    name: Deploy V2 docs to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run build

      - name: Docs build
        env:
          NETLIFY: true
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run docs:vite-build

      - name: Combine output
        run: |
          pnpm cpx "docs/blog2/dist/**" dist/blog
          pnpm cpx "docs/comment2/dist/**" dist/comment
          pnpm cpx "docs/components/dist/**" dist/components
          pnpm cpx "docs/copy-code2/dist/**" dist/copy-code
          pnpm cpx "docs/copyright2/dist/**" dist/copyright
          pnpm cpx "docs/feed2/dist/**" dist/feed
          pnpm cpx "docs/lightgallery/dist/**" dist/lightgallery
          pnpm cpx "docs/md-enhance/dist/**" dist/md-enhance
          pnpm cpx "docs/photo-swipe/dist/**" dist/photo-swipe
          pnpm cpx "docs/pwa2/dist/**" dist/pwa
          pnpm cpx "docs/reading-time2/dist/**" dist/reading-time
          pnpm cpx "docs/remove-pwa/dist/**" dist/remove-pwa
          pnpm cpx "docs/redirect/dist/**" dist/redirect
          pnpm cpx "docs/sass-palette/dist/**" dist/sass-palette
          pnpm cpx "docs/search-pro/dist/**" dist/search-pro
          pnpm cpx "docs/seo2/dist/**" dist/seo
          pnpm cpx "docs/sitemap2/dist/**" dist/sitemap
          pnpm cpx "docs/theme/dist/**" dist
          > dist/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v2
          branch: netlify
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

  deploy-gitee-docs:
    name: Deploy V2 docs to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run build

      - name: Docs build
        env:
          BASE: /v2/
          HOSTNAME: https://vuepress-theme-hope.gitee.io/
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run docs:vite-build

      - name: Combine output
        run: |
          pnpm cpx "docs/blog2/dist/**" dist/blog
          pnpm cpx "docs/comment2/dist/**" dist/comment
          pnpm cpx "docs/components/dist/**" dist/components
          pnpm cpx "docs/copy-code2/dist/**" dist/copy-code
          pnpm cpx "docs/copyright2/dist/**" dist/copyright
          pnpm cpx "docs/feed2/dist/**" dist/feed
          pnpm cpx "docs/lightgallery/dist/**" dist/lightgallery
          pnpm cpx "docs/md-enhance/dist/**" dist/md-enhance
          pnpm cpx "docs/photo-swipe/dist/**" dist/photo-swipe
          pnpm cpx "docs/pwa2/dist/**" dist/pwa
          pnpm cpx "docs/reading-time2/dist/**" dist/reading-time
          pnpm cpx "docs/remove-pwa/dist/**" dist/remove-pwa
          pnpm cpx "docs/redirect/dist/**" dist/redirect
          pnpm cpx "docs/sass-palette/dist/**" dist/sass-palette
          pnpm cpx "docs/search-pro/dist/**" dist/search-pro
          pnpm cpx "docs/seo2/dist/**" dist/seo
          pnpm cpx "docs/sitemap2/dist/**" dist/sitemap
          pnpm cpx "docs/theme/dist/**" dist
          > dist/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v2
          branch: gitee
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

  deploy-theme-demo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
          - blog
          - docs
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run build

      - name: Build Netlify Demo
        run: |-
          pnpm --filter theme-${{ matrix.name }}-demo demo:vite-build
          > demo/theme-${{ matrix.name }}/dist/.nojekyll

      - name: Deploy to netlify
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/${{ matrix.name }}-demo
          branch: netlify
          folder: demo/theme-${{ matrix.name }}/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

      - name: Build Gitee Demo
        env:
          BASE: /${{ matrix.name }}-demo/
          HOSTNAME: https://vuepress-theme-hope.gitee.io/
        run: |-
          pnpm --filter theme-${{ matrix.name }}-demo demo:vite-build
          > demo/theme-${{ matrix.name }}/dist/.nojekyll

      - name: Deploy to gitee
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/${{ matrix.name }}-demo
          branch: gitee
          folder: demo/theme-${{ matrix.name }}/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

  deploy-plugin-demo:
    name: Deploy ${{ matrix.plugin-name }} demo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plugin-name:
          - blog2
          - comment2
          - components
          - copy-code2
          - copyright2
          - feed2
          - lightgallery
          - md-enhance
          - photo-swipe
          - pwa2
          - redirect
          - sass-palette
          - search-pro
          - seo2
          - sitemap2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run build

      - name: Build ${{ matrix.plugin-name }} demo
        env:
          BASE: /${{ matrix.plugin-name }}-demo/
          HOSTNAME: https://vuepress-theme-hope.github.io/
        run: |-
          pnpm --filter ${{ matrix.plugin-name }}-demo demo:vite-build
          > demo/${{ matrix.plugin-name }}/src/.vuepress/dist/.nojekyll

      - name: Deploy ${{ matrix.plugin-name }} demo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/${{ matrix.plugin-name }}-demo
          branch: gh-pages
          folder: demo/${{ matrix.plugin-name }}/src/.vuepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true
