name: Deploy V1 Theme Demo

on:
  push:
    branches:
      - v1

jobs:
  theme-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: restore lerna
        uses: actions/cache@v2
        id: lerna-cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('yarn.lock') }}

      - name: Get yarn cache directory path
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: yarn-cache
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Deps
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn run build

      - name: Build GitHub Pages Demo
        env:
          BASE: /v1-demo/
          HOSTNAME: https://vuepress-theme-hope.github.io/
        run: |
          yarn run demo:build

      - name: Deploy to gh pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v1-demo
          branch: gh-pages
          folder: demo/dist
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Build Netlify Demo
        run: |
          yarn run demo:build

      - name: Deploy to netlify
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v1-demo
          branch: netlify
          folder: demo/dist
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Build Gitee Demo
        env:
          BASE: /v1-demo/
          HOSTNAME: https://vuepress-theme-hope.gitee.io/
        run: |
          yarn run demo:build

      - name: Deploy to gitee
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v1-demo
          branch: gitee
          folder: demo/dist
          token: ${{ secrets.ACCESS_TOKEN }}
