name: Deploy V1 Docs on other places

on:
  push:
    tags:
      - v1.**

jobs:
  deploy-netlify:
    name: Deploy V1 docs to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: restore lerna
        uses: actions/cache@v3
        id: lerna-cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('yarn.lock') }}

      - name: Get yarn cache directory path
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: yarn-cache
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Deps
        run: yarn install --frozen-lockfile

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: yarn run build

      - name: Docs build
        run: yarn run docs:build

      - name: Combine output
        run: |
          yarn cpx "docs/theme/dist/**" dist
          yarn cpx "docs/active-hash/dist/**" dist/active-hash
          yarn cpx "docs/add-this/dist/**" dist/add-this
          yarn cpx "docs/comment/dist/**" dist/comment
          yarn cpx "docs/components/dist/**" dist/components
          yarn cpx "docs/copy-code/dist/**" dist/copy-code
          yarn cpx "docs/feed/dist/**" dist/feed
          yarn cpx "docs/git/dist/**" dist/git
          yarn cpx "docs/md-enhance/dist/**" dist/md-enhance
          yarn cpx "docs/photo-swipe/dist/**" dist/photo-swipe
          yarn cpx "docs/pwa/dist/**" dist/pwa
          yarn cpx "docs/reading-time/dist/**" dist/reading-time
          yarn cpx "docs/seo/dist/**" dist/seo
          yarn cpx "docs/sitemap/dist/**" dist/sitemap

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v1
          branch: netlify
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

  deploy-gitee:
    name: Deploy V1 docs to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: restore lerna
        uses: actions/cache@v3
        id: lerna-cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-lerna-${{ hashFiles('yarn.lock') }}

      - name: Get yarn cache directory path
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: yarn-cache
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Deps
        if: steps.lerna-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn run build

      - name: Build Docs
        env:
          BASE: /v1/
          HOSTNAME: https://vuepress-theme-hope.gitee.io/
        run: yarn run docs:build

      - name: Combine output
        run: |
          yarn cpx "docs/theme/dist/**" dist
          yarn cpx "docs/active-hash/dist/**" dist/active-hash
          yarn cpx "docs/add-this/dist/**" dist/add-this
          yarn cpx "docs/comment/dist/**" dist/comment
          yarn cpx "docs/components/dist/**" dist/components
          yarn cpx "docs/copy-code/dist/**" dist/copy-code
          yarn cpx "docs/feed/dist/**" dist/feed
          yarn cpx "docs/git/dist/**" dist/git
          yarn cpx "docs/md-enhance/dist/**" dist/md-enhance
          yarn cpx "docs/photo-swipe/dist/**" dist/photo-swipe
          yarn cpx "docs/pwa/dist/**" dist/pwa
          yarn cpx "docs/reading-time/dist/**" dist/reading-time
          yarn cpx "docs/seo/dist/**" dist/seo
          yarn cpx "docs/sitemap/dist/**" dist/sitemap

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v1
          branch: gitee
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true
