name: Deploy V1 Theme Demo

on:
  push:
    branches:
      - v1

jobs:
  theme-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Build project
        run: pnpm run build

      - name: Build GitHub Pages Demo
        env:
          BASE: /v1-demo/
          HOSTNAME: https://vuepress-theme-hope.github.io/
        run: |
          pnpm run demo:build

      - name: Deploy to gh pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v1-demo
          branch: gh-pages
          folder: demo/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

      - name: Build Netlify Demo
        run: |
          pnpm run demo:build

      - name: Deploy to netlify
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v1-demo
          branch: netlify
          folder: demo/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

      - name: Build Gitee Demo
        env:
          BASE: /v1-demo/
          HOSTNAME: https://vuepress-theme-hope.gitee.io/
        run: |
          pnpm run demo:build

      - name: Deploy to gitee
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v1-demo
          branch: gitee
          folder: demo/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true
