name: Deploy V1 Docs and demos

on:
  push:
    tags:
      - v1.**

jobs:
  deploy-netlify:
    name: Deploy V1 docs to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Build project
        run: pnpm run build

      - name: Docs build
        run: pnpm run docs:build

      - name: Combine output
        run: |
          pnpm cpx "docs/theme/dist/**" dist
          pnpm cpx "docs/active-hash/dist/**" dist/active-hash
          pnpm cpx "docs/add-this/dist/**" dist/add-this
          pnpm cpx "docs/comment/dist/**" dist/comment
          pnpm cpx "docs/components/dist/**" dist/components
          pnpm cpx "docs/copy-code/dist/**" dist/copy-code
          pnpm cpx "docs/feed/dist/**" dist/feed
          pnpm cpx "docs/git/dist/**" dist/git
          pnpm cpx "docs/md-enhance/dist/**" dist/md-enhance
          pnpm cpx "docs/photo-swipe/dist/**" dist/photo-swipe
          pnpm cpx "docs/pwa/dist/**" dist/pwa
          pnpm cpx "docs/reading-time/dist/**" dist/reading-time
          pnpm cpx "docs/seo/dist/**" dist/seo
          pnpm cpx "docs/sitemap/dist/**" dist/sitemap

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v1
          branch: netlify
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

  deploy-gitee:
    name: Deploy V1 docs to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Build project
        run: pnpm run build

      - name: Build Docs
        env:
          BASE: /v1/
          HOSTNAME: https://vuepress-theme-hope.gitee.io/
        run: pnpm run docs:build

      - name: Combine output
        run: |
          pnpm cpx "docs/theme/dist/**" dist
          pnpm cpx "docs/active-hash/dist/**" dist/active-hash
          pnpm cpx "docs/add-this/dist/**" dist/add-this
          pnpm cpx "docs/comment/dist/**" dist/comment
          pnpm cpx "docs/components/dist/**" dist/components
          pnpm cpx "docs/copy-code/dist/**" dist/copy-code
          pnpm cpx "docs/feed/dist/**" dist/feed
          pnpm cpx "docs/git/dist/**" dist/git
          pnpm cpx "docs/md-enhance/dist/**" dist/md-enhance
          pnpm cpx "docs/photo-swipe/dist/**" dist/photo-swipe
          pnpm cpx "docs/pwa/dist/**" dist/pwa
          pnpm cpx "docs/reading-time/dist/**" dist/reading-time
          pnpm cpx "docs/seo/dist/**" dist/seo
          pnpm cpx "docs/sitemap/dist/**" dist/sitemap

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v1
          branch: gitee
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true
