name: Deploy V2 Docs

on:
  push:
    branches:
      - main

jobs:
  deploy-gh-pages:
    name: Deploy V2 docs to gh pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run build

      - name: Docs build
        env:
          BASE: /v2/
          HOSTNAME: https://vuepress-theme-hope.github.io/
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run docs:vite-build

      - name: Combine output
        run: |
          pnpm cpx "docs/add-this/dist/**" dist/add-this
          pnpm cpx "docs/blog2/dist/**" dist/blog
          pnpm cpx "docs/comment2/dist/**" dist/comment
          pnpm cpx "docs/components/dist/**" dist/components
          pnpm cpx "docs/copy-code2/dist/**" dist/copy-code
          pnpm cpx "docs/copyright2/dist/**" dist/copyright
          pnpm cpx "docs/feed2/dist/**" dist/feed
          pnpm cpx "docs/lightgallery/dist/**" dist/lightgallery
          pnpm cpx "docs/md-enhance/dist/**" dist/md-enhance
          pnpm cpx "docs/photo-swipe/dist/**" dist/photo-swipe
          pnpm cpx "docs/pwa2/dist/**" dist/pwa
          pnpm cpx "docs/reading-time2/dist/**" dist/reading-time
          pnpm cpx "docs/redirect2/dist/**" dist/redirect
          pnpm cpx "docs/sass-palette/dist/**" dist/sass-palette
          pnpm cpx "docs/seo2/dist/**" dist/seo
          pnpm cpx "docs/sitemap2/dist/**" dist/sitemap
          pnpm cpx "docs/theme/dist/**" dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v2
          branch: gh-pages
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true
