name: Deploy V2 Docs and demos

on:
  push:
    tags:
      - v2.**

jobs:
  deploy-netlify-docs:
    name: Deploy V2 docs to Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run build

      - name: Docs build
        env:
          NETLIFY: true
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run docs:vite-build

      - name: Combine output
        run: |
          pnpm cpx "docs/add-this/dist/**" dist/add-this
          pnpm cpx "docs/blog2/dist/**" dist/blog
          pnpm cpx "docs/comment2/dist/**" dist/comment
          pnpm cpx "docs/components/dist/**" dist/components
          pnpm cpx "docs/copy-code2/dist/**" dist/copy-code
          pnpm cpx "docs/copyright2/dist/**" dist/copyright
          pnpm cpx "docs/feed2/dist/**" dist/feed
          pnpm cpx "docs/lightgallery/dist/**" dist/lightgallery
          pnpm cpx "docs/md-enhance/dist/**" dist/md-enhance
          pnpm cpx "docs/photo-swipe/dist/**" dist/photo-swipe
          pnpm cpx "docs/pwa2/dist/**" dist/pwa
          pnpm cpx "docs/reading-time2/dist/**" dist/reading-time
          pnpm cpx "docs/redirect2/dist/**" dist/redirect
          pnpm cpx "docs/redirect2/dist/**" dist/redirect
          pnpm cpx "docs/sass-palette/dist/**" dist/sass-palette
          pnpm cpx "docs/seo2/dist/**" dist/seo
          pnpm cpx "docs/sitemap2/dist/**" dist/sitemap
          pnpm cpx "docs/theme/dist/**" dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v2
          branch: netlify
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

  deploy-gitee-docs:
    name: Deploy V2 docs to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run build

      - name: Docs build
        env:
          BASE: /v2/
          HOSTNAME: https://vuepress-theme-hope.gitee.io/
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run docs:vite-build

      - name: Combine output
        run: |
          pnpm cpx "docs/add-this/dist/**" dist/add-this
          pnpm cpx "docs/blog2/dist/**" dist/blog
          pnpm cpx "docs/comment2/dist/**" dist/comment
          pnpm cpx "docs/components/dist/**" dist/components
          pnpm cpx "docs/copy-code2/dist/**" dist/copy-code
          pnpm cpx "docs/copyright2/dist/**" dist/copyright
          pnpm cpx "docs/feed2/dist/**" dist/feed
          pnpm cpx "docs/lightgallery/dist/**" dist/lightgallery
          pnpm cpx "docs/md-enhance/dist/**" dist/md-enhance
          pnpm cpx "docs/photo-swipe/dist/**" dist/photo-swipe
          pnpm cpx "docs/pwa2/dist/**" dist/pwa
          pnpm cpx "docs/reading-time2/dist/**" dist/reading-time
          pnpm cpx "docs/redirect2/dist/**" dist/redirect
          pnpm cpx "docs/sass-palette/dist/**" dist/sass-palette
          pnpm cpx "docs/seo2/dist/**" dist/seo
          pnpm cpx "docs/sitemap2/dist/**" dist/sitemap
          pnpm cpx "docs/theme/dist/**" dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v2
          branch: gitee
          folder: dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

  deploy-theme-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run build

      - name: Build Netlify Demo
        run: pnpm workspace theme-demo demo:vite-build

      - name: Deploy to netlify
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v2-demo
          branch: netlify
          folder: demo/theme/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

      - name: Build Gitee Demo
        env:
          BASE: /v2-demo/
          HOSTNAME: https://vuepress-theme-hope.gitee.io/
        run: pnpm --filter theme-demo demo:vite-build

      - name: Deploy to gitee
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/v2-demo
          branch: gitee
          folder: demo/theme/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true

  deploy-plugin-demo:
    name: Deploy ${{ matrix.plugin-name }} demo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plugin-name:
          - add-this
          - blog2
          - comment2
          - copy-code2
          - copyright2
          - feed2
          - lightgallery
          - md-enhance
          - photo-swipe
          - pwa2
          - redirect2
          - sass-palette
          - seo2
          - sitemap2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Build project
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm run build

      - name: Build ${{ matrix.plugin-name }} demo
        env:
          BASE: /${{ matrix.plugin-name }}-demo/
          HOSTNAME: https://vuepress-theme-hope.github.io/
        run: pnpm --filter ${{ matrix.plugin-name }}-demo demo:vite-build

      - name: Deploy ${{ matrix.plugin-name }} demo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: vuepress-theme-hope/${{ matrix.plugin-name }}-demo
          branch: gh-pages
          folder: demo/${{ matrix.plugin-name }}/src/.vuepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true
